AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  kaqchikel-translator-functions

  Sample SAM Template for kaqchikel-translator-functions

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 300
    MemorySize: 10240
    Tracing: Active
    Layers:
      - !Sub "arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:14"
  Api:
    TracingEnabled: true
Resources:
  TranslateFunctionV2:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/
      Handler: translate_v2.app.lambda_handler
      Runtime: python3.9
      EphemeralStorage:
        Size: 1024
      Architectures:
      - x86_64
      Events:
        Translate:
          Type: Api
          Properties:
            Path: /translate_v2
            Method: get
          Cors:
            AllowMethods: "'GET, OPTIONS'"
            AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
            AllowOrigin: "'*'"
      Policies:
        - AmazonS3ReadOnlyAccess
        - AmazonSSMReadOnlyAccess
  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/translate/"
  TranslateFunctionV2:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt TranslateFunctionV2.Arn
