AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  kaqchikel-translator-functions

  Sample SAM Template for kaqchikel-translator-functions

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 10240
    Tracing: Active
    Layers:
      - !Sub "arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:14"
  Api:
    TracingEnabled: true
Parameters:
  NewRelicAccountId:
    Type: String
    Description: 'New Relic Account ID'

  NewRelicLicenseKey:
    Type: String
    Description: 'New Relic License Key'
Resources:
  TranslateFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: functions/
      Handler:  translate.app.lambda_handler
      Runtime: python3.9
      Architectures:
      - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /translate
            Method: get
          Cors:
            AllowMethods: "'GET,OPTIONS'"
            AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
            AllowOrigin: "'*'"
      Policies:
        - AmazonS3ReadOnlyAccess
      Environment:
        Variables:
          NEW_RELIC_LICENSE_KEY: !Sub '{{resolve:ssm:/traductor-kaqchikel-functions/NEW_RELIC_LICENSE_KEY}}'
          NEW_RELIC_ACCOUNT_ID: !Sub '{{resolve:ssm:/traductor-kaqchikel-functions/NEW_RELIC_ACCOUNT_ID}}'
      Layers:
        - !Sub "arn:aws:lambda:${AWS::Region}:451483290750:layer:NewRelicPython39:51"

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
  #NewRelicLicenseKeySSMParameter:
  #  Type: 'AWS::SSM::Parameter'
  #  Properties:
  #    Name: '/traductor-kaqchikel-functions/NEW_RELIC_LICENSE_KEY
  #    Type: 'SecureString'
  #    NoEcho: true
  #    Description: 'New Relic License Key'
  #NewRelicAccountIdSSMParameter:
  #  Type: 'AWS::SSM::Parameter'
  #  Properties:
  #    Name: '/traductor-kaqchikel-functions/NEW_RELIC_ACCOUNT_ID'
  #    Type: 'SecureString'
  #    NoEcho: true
  #    Description: 'New Relic Account ID'
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  TranslateFunction:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt TranslateFunction.Arn
  TranslateFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt TranslateFunctionRole.Arn
